#!/bin/bash

##### Script has been generated by the /Users/m1_imac/builds/4ubXge_e/0/eptar/ac-plugins/architerra/../eptar-build-support/archicad/installer/mac/generate_postflight_install_acXX.sh script

# ----------------------------------
# Input params
# ----------------------------------
AC_VERSION="27"
LANGVERSION="GER"
TMPFOLDER="EptarTMP"
APXFOLDER="ArchiTerra"
AC_VER=27
FORCE_DELETE_FOLDER=""

source postflight_install_ac.sh
